### ISSUE TITLE
Error after run an example command in README - AttributeError: 'ScienceWorldEnv' object has no attribute 'get_task_names' 

### ISSUE THREAD

**Issue by pacozaa** [allenai/ScienceWorld#72]
After run `python examples/random_agent.py --task-num=13 --num-episodes=5 --simplifications-preset easy` I got 
```
ScienceWorld 1.0 API Examples - Random Agent
Traceback (most recent call last):
  File "examples/random_agent.py", line 213, in <module>
    main()
  File "examples/random_agent.py", line 209, in main
    randomModel(args)
  File "examples/random_agent.py", line 22, in randomModel
    taskNames = env.get_task_names()
AttributeError: 'ScienceWorldEnv' object has no attribute 'get_task_names'
```

**Comment by pacozaa** [comment]
@MarcCote Nice thanks! Let me try.

**Comment by pacozaa** [comment]
@MarcCote It's working! Thanks. Maybe you can include build from source guide? for next next people.

**Comment by MarcCote** [comment]
Great. Thanks for the suggestion. I have updated the README.
